[package]
name = "a1-Woerter-aufraeumen"
version = "0.1.0"
authors = ["Noél Sigmunczyk <noelsigmunczyk@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
